spring:
    application:
        name: shipping-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://db-shipping:5432/microservice_shipped_products
        username: postgres
        password: deeplearning
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8040

management:
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always




