spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service
            uri: http://localhost:8050
            predicates:
              - Path=/api/v1/products/**
server:
  port: 8020

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always