grpc:
  client:
    product-service:
      address: "localhost:8050"
      negotiation-type: plaintext
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?currentSchema=orders
    username: postgres
    password: Deeplearning89629202@#$!
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8030


management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always


