server:
  port: 8050
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?currentSchema=products
    username: postgres
    password: Deeplearning89629202@#$!
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
grpc:
  server:
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


